name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls
      - run: cd Frontend
      - name: Install dependencies
        run: yarn install
      - name: build frontend
        run: yarn run build
      - name: run test
        run: yarn run test --watchAll
  
  build-and-deploy-back:
    needs: [build-test]
    name: Build and Deploy Back-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: popemorris/shiftplanner-backend
          dockerfile: Backend/Dockerfile
          tags: latest
          
  build-and-deploy-front:
    needs: [build-test]
    name: Build and Deploy Front-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: popemorris/shiftplanner-frontend
          dockerfile: Frontend/Dockerfile
          tags: latest
